<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lab4.Contracts\Lab4.Contracts.csproj" />
    <ProjectReference Include="..\Lab4.RabbitMq\Lab4.RabbitMq.csproj" />
  </ItemGroup>

</Project>
