<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Lab4.TopicWorker-84be1510-3af4-40d5-92a8-905df6eaac7a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lab4.Contracts\Lab4.Contracts.csproj" />
    <ProjectReference Include="..\Lab4.RabbitMq\Lab4.RabbitMq.csproj" />
  </ItemGroup>
</Project>
